#!groovy

// Generated by IBM TransformationAdvisor
// Thu Jun 27 03:35:58 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'plantsbywebspherev8'
    mvnCommands = '--version'
    test='false'
}