#!groovy

// Generated by IBM TransformationAdvisor
// Mon Jun 17 09:07:04 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'plantsbywebspherev8'
    mvnCommands = '--version'
    test='false'
}